FROM gcr.io/tensorflow/tensorflow:latest-gpu-py3

LABEL maintainer="Jiaqing Lin"

WORKDIR /root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        pkg-config \
        libglew-dev \
        libjpeg8-dev \
        libtiff5-dev \
        libjasper-dev \
        libpng12-dev \
        libavcodec-dev \
        libavformat-dev \
        libswscale-dev \
        libv4l-dev \
        libxvidcore-dev \
        libfaac-dev libgpac-dev \
        libx265-dev libx264-dev libfdk-aac-dev \
        libavutil-dev \
        libavdevice-dev \
        libavfilter-dev \
        libpostproc-dev \
        libgtk-3-dev \
        libatlas-base-dev \
        libgoogle-glog-dev libgflags-dev \
        ocl-icd-opencl-dev libprotobuf-dev protobuf-compiler \
        libeigen3-dev \
        libtbb-dev \
        libboost-all-dev \
        gfortran \
        python3-dev \
        python3-numpy \
        python3-dbg \
        python3-pip \
        python3-tk \
        git \
        wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install \
    tqdm \
    youtube_dl

# Download OpenCV 3.x.x latest version and install
RUN cd ~ && \
    rm -rf opencv && \
    rm -rf opencv_contrib && \
    git clone https://github.com/opencv/opencv.git && \
    git clone https://github.com/opencv/opencv_contrib.git && \
    cd /root/opencv && \
    mkdir build && \
    cd build && \
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
          -D CMAKE_INSTALL_PREFIX=/usr/local \
          -D INSTALL_C_EXAMPLES=OFF \
          -D INSTALL_PYTHON_EXAMPLES=OFF \
          -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
          -D WITH_FFMPEG=ON \
          -D WITH_CUDA=ON \
          -D CUDA_NVCC_FLAGS="-D_FORCE_INLINES" \
          -D ENABLE_FAST_MATH=ON \
          -D CUDA_FAST_MATH=ON \
          -D WITH_CUBLAS=ON \
	      -D WITH_TBB=ON \
	      -D WITH_V4L=ON \
          -D BUILD_opencv_python3=ON \
	      -D BUILD_PERF_TESTS=OFF \
	      -D BUILD_TESTS=OFF \
          -D BUILD_EXAMPLES=OFF .. && \
    cd ~/opencv/build && \
    make -j $(nproc) && \
    make install && \
    ldconfig && \
    # clean opencv repos
    rm -rf ~/opencv/build && \
    rm -rf ~/opencv/3rdparty && \
    rm -rf ~/opencv/doc && \
    rm -rf ~/opencv/include && \
    rm -rf ~/opencv/platforms && \
    rm -rf ~/opencv/modules && \
    rm -rf ~/opencv_contrib/build && \
    rm -rf ~/opencv_contrib/doc