FROM nvidia/cuda:9.1-cudnn7-devel-ubuntu16.04

LABEL maintainer="Jiaqing Lin"

WORKDIR /root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        apt-utils \
        cmake \
        curl \
        git \
        unzip \
        vim \
        wget \
        nasm \
        python3 \
        python3-dev \
        python3-dbg \
        python3-pip \
        python3-tk \
        build-essential \
        pkg-config \
        libglew-dev \
        libjpeg8-dev \
        libtiff5-dev \
        libjasper-dev \
        libpng12-dev \
        libgtk2.0-dev \
        libavcodec-dev \
        libavformat-dev \
        libavutil-dev \
        libavdevice-dev \
        libavfilter-dev \
        libpostproc-dev \
        libswresample-dev \
        libfaac-dev libgpac-dev \
        libx265-dev libx264-dev libfdk-aac-dev \
        libswscale-dev \
        libv4l-dev \
        libatlas-base-dev \
        gfortran \
        libhdf5-dev \
        zlib1g-dev \
        libeigen3-dev \
        libtbb-dev \
        libboost-all-dev libgoogle-glog-dev libgflags-dev \
        ocl-icd-opencl-dev libprotobuf-dev protobuf-compiler \
        ffmpeg && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir --upgrade pip
RUN pip3 install \
    numpy \
    matplotlib \
    scipy \
    scikit-learn \
    tqdm \
    youtube_dl \
    pandas \
    pillow \
    h5py \
    joblib

RUN pip3 install http://download.pytorch.org/whl/cu91/torch-0.4.0-cp35-cp35m-linux_x86_64.whl
RUN pip3 install torchvision

# Download OpenCV 3.x.x latest version and install
RUN cd ~ && \
    rm -rf opencv && \
    rm -rf opencv_contrib && \
    git clone https://github.com/opencv/opencv.git && \
    git clone https://github.com/opencv/opencv_contrib.git && \
    cd /root/opencv_contrib && git checkout 3.4.0 && \
    cd /root/opencv && git checkout 3.4.0 && \
    mkdir build && \
    cd build && \
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
          -D CMAKE_INSTALL_PREFIX=/usr/local \
          -D INSTALL_C_EXAMPLES=OFF \
          -D INSTALL_PYTHON_EXAMPLES=OFF \
          -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
          -D WITH_FFMPEG=ON \
          -D WITH_CUDA=ON \
          -D CUDA_NVCC_FLAGS="-D_FORCE_INLINES" \
          -D ENABLE_FAST_MATH=ON \
          -D CUDA_FAST_MATH=ON \
          -D WITH_CUBLAS=ON \
	      -D WITH_TBB=ON \
          -D WITH_LIBV4L=ON \
          -D BUILD_opencv_python3=ON \
	      -D BUILD_PERF_TESTS=OFF \
	      -D BUILD_TESTS=OFF \
          -D BUILD_EXAMPLES=OFF .. && \
    cd ~/opencv/build && \
    make -j $(nproc) && \
    make install && \
    ldconfig && \
    # clean opencv repos
    rm -rf ~/opencv/build && \
    rm -rf ~/opencv/3rdparty && \
    rm -rf ~/opencv/doc && \
    rm -rf ~/opencv/include && \
    rm -rf ~/opencv/platforms && \
    rm -rf ~/opencv/modules && \
    rm -rf ~/opencv_contrib/build && \
    rm -rf ~/opencv_contrib/doc
